return {
	-- "dense-analysis/ale",
	-- config = function()
	-- 	-- local ale = require("dense-analysis/ale")
	-- 	--
	-- 	-- ale.setup({
	-- 	-- 	linters = {
	-- 	-- 		["javascript"] = { "eslint", "prettier" },
	-- 	-- 		["typescript"] = { "eslint", "prettier" },
	-- 	-- 	},
	-- 	-- 	fixers = {
	-- 	-- 		["javascript"] = { "eslint", "prettier" },
	-- 	-- 		["typescript"] = { "eslint", "prettier" },
	-- 	-- 	},
	-- 	-- 	settings = {
	-- 	-- 		ale = {
	-- 	-- 			lint_on_save = 1,
	-- 	-- 		},
	-- 	-- 	},
	-- 	-- })
	-- end
}
